Repository jshi213/Smalt, pull requests merged in 2021-05, with the labels that each got.

#17 Add playlist table to homepage
  frontend/src/homePage/index.js
  frontend/src/homePage/style.module.css
Labels: enhancement

#18 Set up backend database
  backend/db/schema.js
Labels: enhancement

#25 added backend API endpoint for searching songs through spotify API
  backend/routes/index.js
  backend/routes/search.js
  backend/utils/formatter.js
  backend/utils/spotify.js
Labels: enhancement

#29 removed duplicate file and refactored imports
  backend/Spotify/spotifyHandler.js
  backend/routes/search.js
  backend/routes/users.js
  backend/utils/spotify.js
Labels: bug

#36 Added searchfield suggestions in homepage
  backend/Spotify/spotifyHandler.js
  backend/routes/search.js
  frontend/src/homePage/index.js
  frontend/src/homePage/style.module.css
  frontend/src/landingPage/index.js
Labels: enhancement

#35 remove inline css
  frontend/src/homePage/index.js
  frontend/src/homePage/style.module.css
  frontend/src/joinPlaylistPage/index.js
  frontend/src/landingPage/index.js
Labels: refactor

#34 Add createroom DB query and update authcode endpoint to add room to DB
  backend/db/connect.js
  backend/db/queries.js
  backend/db/schema.js
  backend/db/test.js
  backend/package-lock.json
  backend/package.json
  backend/routes/users.js
  frontend/src/hostPage/index.js
Labels: bug, enhancement

#46 Refactored components from page files, css update and minor fixes
  backend/db/schema.js
  backend/routes/search.js
  frontend/public/favicon.ico
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/src/App.js
  frontend/src/AppContextProvider.js
  frontend/src/components/CodeInput/index.js
  frontend/src/components/CodeInput/style.module.css
  frontend/src/components/HostCreateRoom/index.js
  frontend/src/components/HostCreateRoom/style.module.css
  frontend/src/components/LandingOptions/index.js
  frontend/src/components/LandingOptions/style.module.css
  frontend/src/components/Playlist/index.js
  frontend/src/components/Playlist/style.module.css
  frontend/src/components/SongSearch/index.js
  frontend/src/components/SongSearch/style.module.css
  frontend/src/components/index.js
  frontend/src/homePage/index.js
  frontend/src/homePage/style.module.css
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/joinPlaylistPage/index.js
  frontend/src/landingPage/index.js
  frontend/src/landingPage/style.module.css
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.module.css
  frontend/src/pages/HostPage/index.js
  frontend/src/pages/HostPage/style.module.css
  frontend/src/pages/JoinPlaylistPage/index.js
  frontend/src/pages/JoinPlaylistPage/style.module.css
  frontend/src/pages/LandingPage/index.js
  frontend/src/pages/LandingPage/style.module.css
  frontend/src/pages/index.js
Labels: bug, refactor

#47 Refactor CSS and update button components
  frontend/src/components/CodeInput/index.js
  frontend/src/components/CodeInput/style.module.css
  frontend/src/components/HostCreateRoom/index.js
  frontend/src/components/HostCreateRoom/style.module.css
  frontend/src/components/Playlist/index.js
  frontend/src/components/Playlist/style.module.css
  frontend/src/components/SongSearch/index.js
  frontend/src/components/SongSearch/style.module.css
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.module.css
Labels: bug, refactor

#54 Added functionality to add song to DB from suggestions dropdown
  backend/Spotify/spotifyHandler.js
  backend/app.js
  backend/db/schema.js
  backend/routes/search.js
  backend/routes/users.js
  frontend/src/components/Playlist/index.js
  frontend/src/components/SongSearch/index.js
Labels: enhancement

#56 added async awaits in testdb and queries
  backend/db/queries.js
  backend/db/test.js
Labels: bug

#65 Changed back and menu buttons to icons
  frontend/src/components/CodeInput/index.js
  frontend/src/components/CodeInput/style.module.css
  frontend/src/components/HostCreateRoom/index.js
  frontend/src/components/HostCreateRoom/style.module.css
  frontend/src/components/SongSearch/style.module.css
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.module.css
Labels: enhancement

#75 Rearrange song component elements and add like button
  frontend/src/components/Song/index.js
Labels: enhancement

#81 added DB queries and backend endpoints for liking and removing like from songs
  backend/Sockets/socketMgr.js
  backend/db/queries.js
  backend/db/test.js
  backend/routes/users.js
Labels: enhancement

#79 fixed refresh token, fixed join room page, will fix sockets
  backend/Spotify/spotifyHandler.js
  backend/db/queries.js
  backend/db/test.js
  backend/routes/index.js
  backend/routes/search.js
  frontend/src/components/CodeInput/index.js
Labels: bug

#83 Like buttons for songs now reflect changes in DB
  backend/Sockets/socketMgr.js
  backend/db/queries.js
  backend/routes/users.js
  frontend/src/components/Playlist/index.js
  frontend/src/components/Song/index.js
Labels: enhancement

#84 Bugfixes
  backend/Sockets/socketMgr.js
  backend/db/test.js
  frontend/src/components/Playlist/index.js
Labels: bug

#90 Db refactor
  backend/Sockets/socketMgr.js
  backend/Spotify/spotifyHandler.js
  backend/app.js
  backend/db/connect.js
  backend/db/hostSchema.js
  backend/db/queries.js
  backend/db/roomSchema.js
  backend/db/test.js
  backend/routes/host.js
  backend/routes/index.js
  backend/routes/search.js
  backend/routes/users.js
  frontend/src/components/HostCreateRoom/index.js
  frontend/src/components/Song/index.js
  frontend/src/pages/HomePage/index.js
  frontend/src/pages/HomePage/style.module.css
  frontend/src/pages/HostPage/index.js
Labels: refactor

#95 added check for duplicate song when adding song
  backend/db/queries.js
  backend/routes/join.js
  frontend/src/components/Playlist/index.js
  frontend/src/components/SongSearch/index.js
  frontend/src/useSessionStorage.js
Labels: bug

#108 Issue#97
  backend/Spotify/spotifyHandler.js
  backend/db/queries.js
  backend/routes/host.js
  frontend/src/components/CurrentSong/index.js
  frontend/src/components/CurrentSong/style.module.css
  frontend/src/components/HostCreateRoom/index.js
  frontend/src/components/Playlist/index.js
  frontend/src/components/index.js
Labels: enhancement
